 **1. Dataset description**

I have used the Emission  by countries dataset for this experiment. The dataset is consist the polution caused by different fuel source produced by a country in span of many years.

**2. Import libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import warnings
warnings.filterwarnings('ignore')

**3.Import dataset**

In [ ]:
data = '/content/drive/MyDrive/ADS/GCB2022v27_MtCO2_flat.csv'

df = pd.read_csv(data)

**4. Imputation Techniques**

In [ ]:
df.shape

(63104, 11)

In [ ]:
na_variables = [ var for var in df.columns if df[var].isnull().mean() > 0 ]
na_variables

['ISO 3166-1 alpha-3',
 'Total',
 'Coal',
 'Oil',
 'Gas',
 'Cement',
 'Flaring',
 'Other',
 'Per Capita']

In [ ]:
data_na = df[na_variables].isnull().mean()
data_na

ISO 3166-1 alpha-3    0.025862
Total                 0.003169
Coal                  0.655426
Oil                   0.655854
Gas                   0.657423
Cement                0.670164
Flaring               0.658500
Other                 0.974328
Per Capita            0.699322
dtype: float64

In [ ]:
## Implementing the CCA techniques to remove Missing Data
data_cca = df.dropna(axis=0)  ### axis=0 is used for specifying rows
df.shape,data_cca.shape
data_cca.to_csv(r'C:\Users\Aman\Desktop\Emission.csv')

**4. Arbitrary Value Imputation**

In [ ]:
## Finding the columns that have Null Values(Missing Data)
## We are using a for loop for all the columns present in dataset with average null values greater than 0

na_variables = [ var for var in df.columns if df[var].isnull().mean() > 0 ]
na_variables

['ISO 3166-1 alpha-3',
 'Total',
 'Coal',
 'Oil',
 'Gas',
 'Cement',
 'Flaring',
 'Other',
 'Per Capita']

In [ ]:
## Use Country column to find the unique values in the column
df['Total'].unique()

array([0.00000000e+00, 1.46560000e-02, 8.42720000e-02, ...,
       3.70825590e+04, 3.52640857e+04, 3.71238504e+04])

In [ ]:
## Here nan represent Missing Data
## Using Arbitary Imputation technique, we will Impute missing Gender with "Missing"  {You can use any other value also}
arb_impute = df['Total'].fillna('Missing')
arb_impute.unique()

array([0.0, 0.014656, 0.084272, ..., 37082.558969, 35264.085734,
       37123.850352], dtype=object)

**5. Frequent Category Imputation**

In [ ]:
## finding the count of unique values in Gender
df['Total'].groupby(df['Total']).count()

Total
0.000000        41207
0.000032            1
0.000040            2
0.000048            1
0.000049            1
                ...
35577.534774        1
36096.739276        1
36826.506600        1
37082.558969        1
37123.850352        1
Name: Total, Length: 16193, dtype: int64

In [ ]:
## Male has higgest frequency. We can also do it by checking the mode
df['Oil'].mode()

0    0.0
dtype: float64

In [ ]:
## Using Frequent Category Imputer
frq_impute = df['Total'].fillna('0')
frq_impute.unique()

array([0.0, 0.014656, 0.084272, ..., 37082.558969, 35264.085734,
       37123.850352], dtype=object)