Aman Lohani BE-B-25 EXP5

**1. Dataset description**

I have used the Emission by countries dataset for this experiment. The dataset is consist the polution caused by different fuel source produced by a country in span of many years.

**2. Import libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import *
from sklearn.model_selection import train_test_split
import math

In [ ]:
import warnings
warnings.filterwarnings('ignore')

**3.Import dataset**

In [ ]:
data = '/content/drive/MyDrive/ADS/Emission.csv'
df = pd.read_csv(data)
df.head()

,Unnamed: 0,Country,ISO 3166-1 alpha-3,Year,Total,Coal,Oil,Gas,Cement,Flaring,Other,Per Capita
0,3232,Australia,AUS,1990,278.154156,141.879819,88.842090,34.454816,3.462872,7.272496,2.242063,16.315938
1,3233,Australia,AUS,1991,279.528510,146.082840,88.245572,32.786243,3.183033,7.001201,2.229622,16.184767
2,3234,Australia,AUS,1992,284.525345,150.051381,87.916828,33.970472,2.923411,7.303701,2.359551,16.293502
3,3235,Australia,AUS,1993,288.870537,150.098575,90.386578,35.670002,3.004698,7.136743,2.573941,16.383765
4,3236,Australia,AUS,1994,293.696553,151.376241,91.924087,37.032005,3.484276,6.880148,2.999795,16.494706

**4. Training model**

In [ ]:
y_true=df[['Flaring']]
y=df.Total
lm=LinearRegression()
lm.fit(y_true,y)
y_pred=lm.predict(y_true)
print(y_pred)

[  903.63886444   879.6975379    906.39265311 ... 39025.27779484
 36230.42560422 37019.53232726]

**MAE**

In [ ]:
mae = mean_absolute_error(y , y_pred)
print(mae)

596.8773927338403

**RMSE**

In [ ]:
mse = mean_squared_error(y_true, y_pred)
rmse = math.sqrt(mse)
print(rmse)

1237.9928453927232

In [ ]:
print('MAPE:', mean_absolute_percentage_error(y_true, y_pred))

MAPE: 1.6607562851948323e+17

**MAPE**

In [ ]:
# Choose features and target variable
X = df[['Other'	,'Per Capita']]
y = df['Total']
lm=LinearRegression()
lm.fit(X,y)
y_pred=lm.predict(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
print('MAPE:', mape)

MAPE: 4357.37035011023

**MASE**

In [ ]:
y = df['Total']
train_size = int(len(y) * 0.8)
train, test = y[0:train_size], y[train_size:len(y)]
naive_forecast = test.shift(1).bfill()
maenaive = np.mean(abs(test - naive_forecast))
print('MAE Naive:', maenaive)

MAE Naive: 179.79112669444444

In [ ]:
MASE=mae/maenaive
print('MASE:', MASE)

MASE: 3.3198378791420295

In [ ]:
naive = df['Total'].shift(1)
MASE = np.mean(np.abs(y-y_pred))/np.mean(np.abs(y-naive))
MASE

9.35811199408865